# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    remember-me:
      key: f0186c13d2417f4fa9532017dc5e02300d6c232d
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jhipsterHazelcastSampleApplication
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
